version: "3"
services:
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.3.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.3.0"
    ports:
      - "5601:5601"
    links:
      - es:elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
  influx:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    links:
      - influx:influx
    volumes:
      - grafana-data:/var/lib/grafana
    
volumes:
  es-data:
  kibana-data:
  influx-data:
  grafana-data:
